### ISSUE TITLE
Error: Action failed because of: TypeError: Cannot destructure property `name` of 'undefined' or 'null'.

### ISSUE THREAD

**Issue by felixk** [derberg/global-workflows-support#1]
Thanks for this code...

I tried to set this up, and I get this error message when I run the action on my .github repo:

```Error: Action failed because of: TypeError: Cannot destructure property `name` of 'undefined' or 'null'.```

This happens right after this message:
```Getting list of repositories owned by NuBanko that will get updates. The following repos will be later ignored: [my ignored repos],.github```

Any ideas what could be wrong. My workflow file looks like this:

```
name: Global workflow Update

on:
  push:
      branches: [ master ] #or main

jobs:

  replicate_changes:

      runs-on: ubuntu-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@v2
        - name: Replicating global workflow
          uses: derberg/global-workflows-support@v0.0.2
          with:
            github_token: ${{ secrets.CUSTOM_TOKEN }}
            files_to_ignore: globalworkflows.yml
            repos_to_ignore: [list comma delimted]
            committer_username: [my username]
            committer_email: [my email]
            commit_message: "ci: update global workflows"
```
